name: NetEase Cloud Music API
version: "0.1.1"
slug: netease_cloud_music_api
description: NetEase Cloud Music API service for Music Assistant.
url: https://github.com/NeteaseCloudMusicApiEnhanced/api-enhanced
startup: services
boot: auto
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: NetEase API HTTP
